
const products = {
    0: {name: "Хлеб ржаной на закваске",
        description: "Мука, вода, соль и никакой химии ",
        price: "150 р.",
        img: "../img/cake-feature/c-feature-1.jpg",
        id: "1",
        specification: "Компонент1, Компонент2, Компонент3, Мука, Волшебство",
        fulldescription: "Бла-Бла-Бла"},
    1: {name: "Домашний синабон",
        description: "Добашний вариант знаменитого лакомства",
        price: "95 р.",
        img: "../img/cake-feature/c-feature-2.jpg",
        id: "2",
        specification: "Компонент1, Компонент2, Компонент3, Мука, Волшебство",
        fulldescription: "Бла-Бла-Бла"},
    2: {name: "Плюшка с сахаром",
        description: "Ароматное дополнение к утреннему кофе ",
        price: "50 р.",
        img: "../img/cake-feature/c-feature-3.jpg",
        id: "3",
        specification: "Компонент1, Компонент2, Компонент3, Мука, Волшебство",
        fulldescription: "Бла-Бла-Бла"},
    3: {name: "Медовый ржаной пряник",
        description: "Лакомство с медом, корицей, имбирем и теплотой рук",
        price: "100 р.",
        img: "../img/cake-feature/c-feature-4.jpg",
        id: "4",
        specification: "Компонент1, Компонент2, Компонент3, Мука, Волшебство",
        fulldescription: "Бла-Бла-Бла"},
    4: {name: "Classic French Croissant",
        description: "Chocolate puding, vanilla, fruite rasberry jam milk ",
        price: "$6.79",
        img: "../img/cake-feature/c-feature-5.jpg",
        id: "5",
        specification: "Компонент1, Компонент2, Компонент3, Мука, Волшебство",
        fulldescription: "Бла-Бла-Бла"},
    5: {name: "Macarons & Tea",
        description: "Chocolate puding, vanilla, fruite rasberry jam evporate milk",
        price: "$5.99",
        img: "../img/cake-feature/c-feature-6.jpg",
        id: "6",
        specification: "Компонент1, Компонент2, Компонент3, Мука, Волшебство",
        fulldescription: "Бла-Бла-Бла"},
    6: {name: "Strawberry Sweet Cake",
        description: "Chocolate puding, vanilla, fruite rasberry jam milk ",
        price: "$12.99",
        img: "../img/cake-feature/arivals-1.jpg",
        id: "7",
        specification: "Компонент1, Компонент2, Компонент3, Мука, Волшебство",
        fulldescription: "Бла-Бла-Бла"},
    7: {name: "Cupcake of Vanela",
        description: "Chocolate puding, vanilla, fruite rasberry jam evporate milk",
        price: "$20.00",
        img: "../img/cake-feature/arivals-2.jpg",
        id: "8",
        specification: "Компонент1, Компонент2, Компонент3, Мука, Волшебство",
        fulldescription: "Бла-Бла-Бла"},
    8: {name: "Торт Панчо с ананасами",
        description: "Chocolate puding, vanilla, fruite rasberry jam milk ",
        price: "600 р.",
        img: "../img/cake-feature/bakery2.jpg",
        id: "9",
        specification: "Компонент1, Компонент2, Компонент3, Мука, Волшебство",
        fulldescription: "Бла-Бла-Бла"},
    9: {name: "Blueberry Muffin",
        description: "CChocolate puding, vanilla, fruite rasberry jam evporate milk",
        price: "$12.99",
        img: "../img/cake-feature/c-feature-1.jpg",
        id: "10",
        specification: "Компонент1, Компонент2, Компонент3, Мука, Волшебство",
        fulldescription: "Бла-Бла-Бла"},
    10: {name: "Double Chocolate Pie",
        description: "Chocolate puding, vanilla, fruite rasberry jam milk ",
        price: "$5.99",
        img: "../img/cake-feature/c-feature-2.jpg",
        id: "11",
        specification: "Компонент1, Компонент2, Компонент3, Мука, Волшебство",
        fulldescription: "Бла-Бла-Бла"},
    11: {name: "Strawberry Sweet Cake",
        description: "Chocolate puding, vanilla, fruite rasberry jam evporate milk",
        price: "$6.79",
        img: "../img/cake-feature/c-feature-3.jpg",
        id: "12",
        specification: "Компонент1, Компонент2, Компонент3, Мука, Волшебство",
        fulldescription: "Бла-Бла-Бла"},
    12: {name: "Bialy Egg Sandwich with Cake",
        description: "Chocolate puding, vanilla, fruite rasberry jam milk ",
        price: "$7.99",
        img: "../img/cake-feature/c-feature-4.jpg",
        id: "13",
        specification: "Компонент1, Компонент2, Компонент3, Мука, Волшебство",
        fulldescription: "Бла-Бла-Бла"},
    13: {name: "Branch Special Cake",
        description: "Chocolate puding, vanilla, fruite rasberry jam evporate milk",
        price: "$8.99",
        img: "../img/cake-feature/c-feature-5.jpg",
        id: "14",
        specification: "Компонент1, Компонент2, Компонент3, Мука, Волшебство",
        fulldescription: "Бла-Бла-Бла"},
    14: {name: "Multigrain Hot Cake",
        description: "Chocolate puding, vanilla, fruite rasberry jam milk ",
        price: "$12.99",
        img: "../img/cake-feature/c-feature-6.jpg",
        id: "15",
        specification: "Компонент1, Компонент2, Компонент3, Мука, Волшебство",
        fulldescription: "Бла-Бла-Бла"},
    15: {name: "Fried Egg Sandwich",
        description: "Chocolate puding, vanilla, fruite rasberry jam evporate milk",
        price: "$8.99",
        img: "../img/cake-feature/c-feature-7.jpg",
        id: "16",
        specification: "Компонент1, Компонент2, Компонент3, Мука, Волшебство",
        fulldescription: "Бла-Бла-Бла"}
}

const discoverProducts = {
    0: {name: "Пшеничный багет на закваске",
        description: "Мука, вода, соль и никакой химии ",
        price: "150 руб.",
        img: "../img/cake-feature/c-feature-7.jpg",
        id: "1",
        specification: "Компонент1, Компонент2, Компонент3, Мука, Волшебство",
        fulldescription: "Бла-Бла-Бла"},
    1: {name: "Морковный кекс",
        description: "Нежнейшее лакомство из необычного ингридиента",
        price: "95 руб.",
        img: "../img/cake-feature/c-feature-7.jpg",
        id: "12",
        specification: "Компонент1, Компонент2, Компонент3, Мука, Волшебство",
        fulldescription: "Бла-Бла-Бла"},
    2: {name: "Печенье юбилейное",
        description: "Ароматное дополнение к утреннему кофе ",
        price: "50 руб.",
        img: "../img/cake-feature/c-feature-7.jpg",
        id: "5",
        specification: "Компонент1, Компонент2, Компонент3, Мука, Волшебство",
        fulldescription: "Бла-Бла-Бла"},
    3: {name: "Постный шоколадный манник",
        description: "Выпечка без муки",
        price: "100 руб.",
        img: "../img/cake-feature/c-feature-7.jpg",
        id: "4",
        specification: "Компонент1, Компонент2, Компонент3, Мука, Волшебство",
        fulldescription: "Бла-Бла-Бла"},
    4: {name: "Бискотти",
        description: "Популярное итальянское печенье",
        price: "$6.79",
        img: "../img/cake-feature/c-feature-7.jpg",
        id: "9",
        specification: "Компонент1, Компонент2, Компонент3, Мука, Волшебство",
        fulldescription: "Бла-Бла-Бла"},
}

export function getProducts(){
    return products;
}

export function getDiscoverProducts(){
    return discoverProducts;
}

export function getProduct(p_index){
    return products[p_index-1];//объекты с нуля, id с 1.
}